# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Chiron Barlangja
email: geryxyz@inf.u-szeged.hu
description: >- # this means to ignore newlines until "baseurl:"
  Ez az oldal a Szegedi Tudományegyetem Szoftverfejlesztés Tanszéke
  által oktatott Rendszerfejlesztés II. tárgyhoz kapcsolódó szakmai anyagokat gyüjti össze.
  A gyűjtést a hallgatók órai feladat keretében végezték.
  A master branch tartalma az oktatók jóváhagyásával módosítható.
baseurl: "/cave-of-chiron"
github_username: geryxyz
minimal_mistakes_skin: default
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Szegedi Tudományegyetem, Szoftverfejlesztés tanszék"
  avatar : "/assets/images/SZTE_crest.png"
  links:
    - label: "Hivatalos oldal"
      icon: "fas fa-fw fa-link"
      url: "https://www.inf.u-szeged.hu/sed"

footer:
  links: None

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      toc: true
      toc_sticky: true
      toc_label: "Ezen az oldalon"


category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

head_scripts:
  - https://kit.fontawesome.com/010718a7db.js